import httpx
from .config import get_settings
from .models import ReviewResult

settings = get_settings()
GITHUB_BASE = "https://api.github.com"


def _headers():
    return {
        "Authorization": f"Bearer {settings.github_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }


async def get_pr_diff(repo: str, pr_number: int) -> str:
    """Fetch the unified diff for a PR."""
    url = f"{GITHUB_BASE}/repos/{repo}/pulls/{pr_number}"
    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.get(
            url,
            headers={**_headers(), "Accept": "application/vnd.github.diff"}
        )
        resp.raise_for_status()
        return resp.text


async def post_review_comment(repo: str, pr_number: int, result: ReviewResult):
    """Post the AI review as a PR review on GitHub."""
    body = _format_review_markdown(result)
    url = f"{GITHUB_BASE}/repos/{repo}/pulls/{pr_number}/reviews"
    # APPROVE if score >= 75 and no critical/high issues
    critical_count = sum(1 for i in result.issues if i.severity in ["critical", "high"])
    event = "APPROVE" if result.approved and critical_count == 0 else "REQUEST_CHANGES"

    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.post(url, headers=_headers(), json={
            "body": body,
            "event": event,
        })
        resp.raise_for_status()


def _format_review_markdown(result: ReviewResult) -> str:
    emoji_map = {
        "critical": "🚨",
        "high": "🔴",
        "medium": "🟡",
        "low": "🟢",
        "info": "ℹ️"
    }
    status = "✅ APPROVED" if result.approved else "❌ CHANGES REQUESTED"
    lines = [
        f"## 🤖 AI Code Review — Score: {result.overall_score}/100  {status}",
        f"**Mode:** `{result.mode.upper()}`\n",
        f"### 📋 Summary\n{result.summary}\n",
        "---\n### 🔍 Issues Found\n"
    ]

    if not result.issues:
        lines.append("_No significant issues found. Great work!_ 🎉")
    else:
        for issue in result.issues:
            em = emoji_map.get(issue.severity, "•")
            lines.append(f"#### {em} [{issue.severity.upper()}] `{issue.category}` — {issue.title}")
            if issue.file:
                loc = f" (line {issue.line})" if issue.line else ""
                lines.append(f"**File:** `{issue.file}`{loc}")
            lines.append(f"\n{issue.explanation}\n")
            lines.append(f"**💡 Suggestion:** {issue.suggestion}")
            if issue.example_code:
                lines.append(f"\n```python\n{issue.example_code}\n```")
            lines.append("\n---")

    lines.append(f"\n_Generated by AI Code Reviewer powered by Google Vertex AI (Gemini)_")
    return "\n".join(lines)
